number_injections: 10000

hw_targets:
  smid: 0
  schid: 1

config_fm:  
  IRA:
    mode: None
  ICOC:
    mode: None
  IIO:
    mode: None
  IAT:
    mode: None
  IAW: 
    mode: None
  IAC: 
    mode: None
  WV:
    mode: None
  IMS: 
    mode: None
  IMD: 
    mode: None
  IAL:
    mode: None
  REGs:
    # mode: "st", "rnd", "stat"
    mode: "st"
    # thread identifier if mode st: if -1 any thread
    thrid: 0
    kname: "gemm"
  FUs:
    # mode: "int32", "fp32", "sfu", "tensor"
    igrp: "FP32_INSTR"
    instrid: ["FFMA", "FMUL", "FADD"]  # if -1 all intructions in the group
    laneid: 0 # line ID (0,16) if -1 random cores, -2 exaustive
    portid: 0 # if -1 indicate random port, 0 indicate output, 1,2,3 input ports, -2 exaustive    
    maskid: 30 # -1 random stuck-at, -2 exhaustive stuck-at, 0 - xxx other extenstions, 





    
      